#!/usr/bin/env bash
set -e

# Clean previous builds
rm -rf dist/ build/ *.egg-info

# Build source distribution and wheel
python3 -m build
echo -n "Ready to upload to PyPI? [press enter]"
read

# Upload to PyPI
python3 -m twine upload dist/*
